 DWAPlannerROS:
    acc_lim_x: 3.0
    acc_lim_theta: 4.0
    max_vel_trans: 0.7
    max_vel_x: 0.7
    max_vel_theta: 1.5
    sim_granularity: 0.07
    sim_time: 2.3
    stop_time_buffer: 0.1  
    angular_sim_granularity: 0.025
    min_vel_x: -0.1
    
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1 
       
