 DWAPlannerROS:
    acc_lim_x: 2.5
    acc_lim_theta: 1.0
    max_vel_trans: 0.55
    max_vel_x: 0.55
    min_vel_x: -0.1
    max_vel_theta: 2.5
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    sim_time: 5.0
    stop_time_buffer: 0.2  
    
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1 
