 DWAPlannerROS:
    acc_lim_x: 2.0
    acc_lim_theta: 2.8
    max_vel_trans: 0.22
    max_vel_x: 0.22
    max_vel_theta: 0.5
    sim_granularity: 0.01
    sim_time: 0.7
    stop_time_buffer: 0.4 
    angular_sim_granularity: 0.025
    min_vel_x: -0.1
    
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1 
       
