// Generated by gencpp from file srl_eband_local_planner/EnableSocialLayer.msg
// DO NOT EDIT!


#ifndef SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYER_H
#define SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYER_H

#include <ros/service_traits.h>


#include <srl_eband_local_planner/EnableSocialLayerRequest.h>
#include <srl_eband_local_planner/EnableSocialLayerResponse.h>


namespace srl_eband_local_planner
{

struct EnableSocialLayer
{

typedef EnableSocialLayerRequest Request;
typedef EnableSocialLayerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableSocialLayer
} // namespace srl_eband_local_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srl_eband_local_planner::EnableSocialLayer > {
  static const char* value()
  {
    return "da9e2563ede369d1290fb3803a11ebb5";
  }

  static const char* value(const ::srl_eband_local_planner::EnableSocialLayer&) { return value(); }
};

template<>
struct DataType< ::srl_eband_local_planner::EnableSocialLayer > {
  static const char* value()
  {
    return "srl_eband_local_planner/EnableSocialLayer";
  }

  static const char* value(const ::srl_eband_local_planner::EnableSocialLayer&) { return value(); }
};


// service_traits::MD5Sum< ::srl_eband_local_planner::EnableSocialLayerRequest> should match
// service_traits::MD5Sum< ::srl_eband_local_planner::EnableSocialLayer >
template<>
struct MD5Sum< ::srl_eband_local_planner::EnableSocialLayerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srl_eband_local_planner::EnableSocialLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srl_eband_local_planner::EnableSocialLayerRequest> should match
// service_traits::DataType< ::srl_eband_local_planner::EnableSocialLayer >
template<>
struct DataType< ::srl_eband_local_planner::EnableSocialLayerRequest>
{
  static const char* value()
  {
    return DataType< ::srl_eband_local_planner::EnableSocialLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srl_eband_local_planner::EnableSocialLayerResponse> should match
// service_traits::MD5Sum< ::srl_eband_local_planner::EnableSocialLayer >
template<>
struct MD5Sum< ::srl_eband_local_planner::EnableSocialLayerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srl_eband_local_planner::EnableSocialLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srl_eband_local_planner::EnableSocialLayerResponse> should match
// service_traits::DataType< ::srl_eband_local_planner::EnableSocialLayer >
template<>
struct DataType< ::srl_eband_local_planner::EnableSocialLayerResponse>
{
  static const char* value()
  {
    return DataType< ::srl_eband_local_planner::EnableSocialLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYER_H
