// Generated by gencpp from file srl_eband_local_planner/EnableSocialLayerRequest.msg
// DO NOT EDIT!


#ifndef SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYERREQUEST_H
#define SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srl_eband_local_planner
{
template <class ContainerAllocator>
struct EnableSocialLayerRequest_
{
  typedef EnableSocialLayerRequest_<ContainerAllocator> Type;

  EnableSocialLayerRequest_()
    : enable(false)  {
    }
  EnableSocialLayerRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnableSocialLayerRequest_

typedef ::srl_eband_local_planner::EnableSocialLayerRequest_<std::allocator<void> > EnableSocialLayerRequest;

typedef boost::shared_ptr< ::srl_eband_local_planner::EnableSocialLayerRequest > EnableSocialLayerRequestPtr;
typedef boost::shared_ptr< ::srl_eband_local_planner::EnableSocialLayerRequest const> EnableSocialLayerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator1> & lhs, const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator1> & lhs, const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srl_eband_local_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srl_eband_local_planner/EnableSocialLayerRequest";
  }

  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request fields\n"
"bool                              enable\n"
;
  }

  static const char* value(const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableSocialLayerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srl_eband_local_planner::EnableSocialLayerRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLESOCIALLAYERREQUEST_H
