// Generated by gencpp from file srl_eband_local_planner/EnableObstacleLayer.msg
// DO NOT EDIT!


#ifndef SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLEOBSTACLELAYER_H
#define SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLEOBSTACLELAYER_H

#include <ros/service_traits.h>


#include <srl_eband_local_planner/EnableObstacleLayerRequest.h>
#include <srl_eband_local_planner/EnableObstacleLayerResponse.h>


namespace srl_eband_local_planner
{

struct EnableObstacleLayer
{

typedef EnableObstacleLayerRequest Request;
typedef EnableObstacleLayerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableObstacleLayer
} // namespace srl_eband_local_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srl_eband_local_planner::EnableObstacleLayer > {
  static const char* value()
  {
    return "da9e2563ede369d1290fb3803a11ebb5";
  }

  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayer&) { return value(); }
};

template<>
struct DataType< ::srl_eband_local_planner::EnableObstacleLayer > {
  static const char* value()
  {
    return "srl_eband_local_planner/EnableObstacleLayer";
  }

  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayer&) { return value(); }
};


// service_traits::MD5Sum< ::srl_eband_local_planner::EnableObstacleLayerRequest> should match
// service_traits::MD5Sum< ::srl_eband_local_planner::EnableObstacleLayer >
template<>
struct MD5Sum< ::srl_eband_local_planner::EnableObstacleLayerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srl_eband_local_planner::EnableObstacleLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srl_eband_local_planner::EnableObstacleLayerRequest> should match
// service_traits::DataType< ::srl_eband_local_planner::EnableObstacleLayer >
template<>
struct DataType< ::srl_eband_local_planner::EnableObstacleLayerRequest>
{
  static const char* value()
  {
    return DataType< ::srl_eband_local_planner::EnableObstacleLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srl_eband_local_planner::EnableObstacleLayerResponse> should match
// service_traits::MD5Sum< ::srl_eband_local_planner::EnableObstacleLayer >
template<>
struct MD5Sum< ::srl_eband_local_planner::EnableObstacleLayerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srl_eband_local_planner::EnableObstacleLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srl_eband_local_planner::EnableObstacleLayerResponse> should match
// service_traits::DataType< ::srl_eband_local_planner::EnableObstacleLayer >
template<>
struct DataType< ::srl_eband_local_planner::EnableObstacleLayerResponse>
{
  static const char* value()
  {
    return DataType< ::srl_eband_local_planner::EnableObstacleLayer >::value();
  }
  static const char* value(const ::srl_eband_local_planner::EnableObstacleLayerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRL_EBAND_LOCAL_PLANNER_MESSAGE_ENABLEOBSTACLELAYER_H
