// Generated by gencpp from file robot1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROBOT1_MESSAGE_ADDTWOINTS_H
#define ROBOT1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <robot1/AddTwoIntsRequest.h>
#include <robot1/AddTwoIntsResponse.h>


namespace robot1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace robot1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::robot1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::robot1::AddTwoInts > {
  static const char* value()
  {
    return "robot1/AddTwoInts";
  }

  static const char* value(const ::robot1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::robot1::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::robot1::AddTwoInts >
template<>
struct MD5Sum< ::robot1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot1::AddTwoInts >::value();
  }
  static const char* value(const ::robot1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1::AddTwoIntsRequest> should match
// service_traits::DataType< ::robot1::AddTwoInts >
template<>
struct DataType< ::robot1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::robot1::AddTwoInts >::value();
  }
  static const char* value(const ::robot1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot1::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::robot1::AddTwoInts >
template<>
struct MD5Sum< ::robot1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot1::AddTwoInts >::value();
  }
  static const char* value(const ::robot1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1::AddTwoIntsResponse> should match
// service_traits::DataType< ::robot1::AddTwoInts >
template<>
struct DataType< ::robot1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::robot1::AddTwoInts >::value();
  }
  static const char* value(const ::robot1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT1_MESSAGE_ADDTWOINTS_H
