#FTCPlanner:
    #max_x_vel: 0.5
    #max_rotation_vel: 1.0
    #acceleration_x: 0.5
    #acceleration_z: 0.5
    #sim_time: 1.0

    ##fijos##
    
   ## slow_down_factor: 2.5
    #join_obstacle: True
    #local_planner_frequence: 5   
    #position_accuracy: 0.2
    #rotation_accuracy: 0.1    

FTCPlanner: 
    max_x_vel: 0.2 
    max_rotation_vel: 0.4 
    min_rotation_vel: 0.1 
    acceleration_x: 0.2 
    acceleration_z: 0.4 
    position_accuracy: 0.10 
    rotation_accuracy: 0.10 
    slow_down_factor: 0 
    sim_time: 1.0 
    local_planner_frequence: 5 
    join_obstacle: false 

