 DWAPlannerROS:
    acc_lim_x: 3.0  
    acc_lim_theta: 1.5
    max_vel_x: 0.7 
    max_vel_theta: 3.0  
    sim_granularity: 0.07
    sim_time: 2.3
    dwa: True
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1 
       
