 DWAPlannerROS:
    acc_lim_x: 2.0 
    acc_lim_theta: 0.5 
    max_vel_x: 0.3 
    max_vel_theta: 2.0  
    sim_granularity: 0.01
    sim_time: 0.7 
    dwa: False
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1 
       
